### ISSUE TITLE
Création de la structure du projet

### ISSUE THREAD

**Issue by tosave04** [parfete/front#1]
Créer la structure de base du projet

- npx create-react-app groupmike --template typescript
- typescript : créer les fichiers en .tsx
- structure des dossiers ? (components, hooks, data ...)
- react-router-dom ?
- gestion des erreurs (ErrorBoundary ?)
- utilisation des Snackbars (ex: react-simple-snackbar) ?

**Comment by IngridDelteil** [comment]
Salut ! 

Pour le nom de l'app je pense qu'il vaut mieux attendre d'avoir choisi le nom plutôt que de l'appeler groupmike. Si ça peut attendre la prochaine réunion ... 😄 

Pour la structure des dossiers on peut planifier ça en vocal à la prochaine réunion aussi.
Pour react-router-dom je valide (je ne vois pas vraiment d'autres alternatives)
Pour la gestion des erreurs je ne connais pas ErrorBoundary
Pour l'utilisation des snackbar c'est pour les mobiles c'est ça ? Pour les messages d'alertes ? Si c'est ça ce n'est peut-être pas utile de se rajouter des dépendances on peut peut-être se coder le composant nous-même.
